name: webcrypto
publish_to: None
description: Dartified interface for web cryptography APIs
author: Jonas Finnemann Jensen <jonasfj@google.com>
homepage: https://user.git.corp.google.com/jonasfj/dart-webcrypto

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.12.0"

dependencies:
  ffi: ^0.1.3
  js: ^0.6.1
  meta: ^1.1.7

dev_dependencies:
  test: ^1.5.2
  yaml: ^2.2.1
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        # This is just a dummy package, so we can use gradle to build the native
        # library with cmake
        package: com.example.flutter_webcrypto_plugin
        pluginClass: FlutterWebcryptoPlugin
